const mongoose = require('mongoose')
const Schema = mongoose.Schema

const billsSchema = new Schema({
    userId:{
        type:Schema.Types.ObjectId,
        ref:'mobileusers'
    },
    name:{
        type:String
    },
    number:{
        type:String
    },
    address:{
        type:String
    },
    PO_no:{
        type:String
    },
    vendorNo:{
        type:String
    },
    GST_no:{
        type:String
    },
    Line_Item_No:{
        type:String
    },
    Challan_No:{
        type:String  
    },
    Vehicle_No:{
        type:String
    },
    Material_Code1:{
        type:String
    },
    Material_Code2:{
        type:String
    },
    Material_Code3:{
        type:String
    },
    Material_Code4:{
        type:String
    },
    Material_Code5:{
        type:String
    },
    Material_TCode1:{
        type:String
    },
    Material_TCode2:{
        type:String
    },
    Material_TCode3:{
        type:String
    },
    Material_TCode4:{
        type:String
    },
    Material_TCode5:{
        type:String
    },
    Quantity1:{
        type:Number,
        default:0
    },
    Quantity2:{
        type:Number,
        default:0
    },
    Quantity3:{
        type:Number,
        default:0
    },
    Quantity4:{
        type:Number,
        default:0
    },
    Quantity5:{
        type:Number,
        default:0
    },
    RQuantity1:{
        type:Number,
        default:0
    },
    RQuantity2:{
        type:Number,
        default:0
    },
    RQuantity3:{
        type:Number,
        default:0
    },
    RQuantity4:{
        type:Number,
        default:0
    },
    RQuantity5:{
        type:Number,
        default:0
    },
    billStatus:{
        type:String,
        default:"Pending"
    },
    TQuantity1:{
        type:Number,
        default:0
    },
    TQuantity2:{
        type:Number,
        default:0
    },
    TQuantity3:{
        type:Number,
        default:0
    },
    TQuantity4:{
        type:Number,
        default:0
    },
    TQuantity5:{
        type:Number,
        default:0
    },
    ExchallanDate1:{
        type:String
    },
    ExchallanDate2:{
        type:String
    },
    ExchallanDate3:{
        type:String
    },
    ExchallanDate4:{
        type:String
    },
    ExchallanDate5:{
        type:String
    },
    ExchallanDate6:{
        type:String
    },
    ExchallanDate7:{
        type:String
    },
    ExchallanDate8:{
        type:String
    },
    ExchallanDate9:{
        type:String
    },
    ExchallanDate10:{
        type:String
    },
    Exchallan1:{
        type:String
    },
    Exchallan2:{
        type:String
    },
    Exchallan3:{
        type:String
    },
    Exchallan4:{
        type:String
    },
    Exchallan5:{
        type:String
    },
    Exchallan6:{
        type:String
    },
    Exchallan7:{
        type:String
    },
    Exchallan8:{
        type:String
    },
    Exchallan9:{
        type:String
    },
    Exchallan10:{
        type:String
    },
    ExQuantity1:{
        type:String
    },
    ExQuantity2:{
        type:String
    },
    ExQuantity3:{
        type:String
    },
    ExQuantity4:{
        type:String
    },
    ExQuantity5:{
        type:String
    },
    ExQuantity6:{
        type:String
    },
    ExQuantity7:{
        type:String
    },
    ExQuantity8:{
        type:String
    },
    ExQuantity9:{
        type:String
    },
    ExQuantity10:{
        type:String
    },
    Painting:{
        type:Boolean
    },
    FinalFettling:{
        type:Boolean
    },
    Qr_Code_URL:{
        type:String,
        default:""
    },
}, {
    timestamps: true
});

module.exports = mongoose.model('bills', billsSchema)